### ISSUE TITLE
用python新写了一个库，用于快速塔建 bot

### ISSUE THREAD

**Issue by lhlyu** [ishkong/go-cqhttp-docs#123]
[cqbot](https://github.com/lhlyu/cqbot)

基本的事件、API都实现了，没有花里胡哨的设计，开发者可以自由发挥

**Comment by SlimeNull** [comment]
不应该因为这个原因而开 issue, 你可以在 Discussions 中开一个讨论, 或者提交一个 PR, 在 "快速开始" 栏目中添加你的 SDK

**Comment by SlimeNull** [comment]
可以关闭这个 issue
