### ISSUE TITLE
[feat]API文档添加绪论

### ISSUE THREAD

**Issue by Ink-33** [ishkong/go-cqhttp-docs#27]
- [ ] 为全部API添加请求与返回例子

现有的`gocq API`文档是建立在用户充分了解`OneBot`协议之上的，对新接触机器人的用户来说并不友好。何况现在的API文档仅描述了`HTTP`的通信方式，对`WS`和`RWS`的实现方法没有提及。综上，我认为有必要在`/api`下添加一个绪论，描述`OneBot API`基本通信原理，并附上`OneBot`的链接。

**Comment by sam01101** [comment]
- [ ] 为全部API添加请求与返回例子

**Comment by SlimeNull** [comment]
喵喵, 我提交了一个 pullrequest (不知道什么时候能被 merge

**Comment by SlimeNull** [comment]
刚开始我看 gocqhttp 文档的时候, 可是一点都看不懂呀, 23333 后来朋友一语点醒梦中人, 原来我还需要看 OneBot 协议, 然后看了 OneBot 协议之后才差不多会用... (说起来 OneBot11 的文档也有些糟糕, 很多地方整理的不好

**Comment by ishkong** [comment]
Merged #80
