### ISSUE TITLE
是否考虑按类别分类展示 API

### ISSUE THREAD

**Issue by qianjunakasumi** [ishkong/go-cqhttp-docs#62]
https://docs.go-cqhttp.org/api/ 下的 item 太多了

如果考虑按类型区别，比如群相关 API、好友相关 API 分门别类放置可能会更利于阅读

想问问大家意见

**Comment by ishkong** [comment]
我觉得可以，但是我想在最近把vuepress版本升到v2.0.0-beta35 不知道sam的v2分支进行的怎么样了，也许你可以先进行分类之后再pr？
@sam01101 Sam觉得可行吗？

**Comment by qianjunakasumi** [comment]
如果升级后变动比较大的话那就先等等吧（

**Comment by sam01101** [comment]
> 我觉得可以，但是我想在最近把vuepress版本升到v2.0.0-beta35 不知道sam的v2分支进行的怎么样了，也许你可以先进行分类之后再pr？ @sam01101 Sam觉得可行吗？

可以分为：群，个人，私聊（临时会话包含在内），频道和其它
或者，以 [OneBot 12](https://12.onebot.dev/) 的分类方法

你们认为哪个比较好

**Comment by qianjunakasumi** [comment]
我觉得前者更直观

**Comment by SlimeNull** [comment]
喵? 如果确认下来要整理的话, 那我就直接去整理文档咯?

**Comment by qianjunakasumi** [comment]
好的喵~

**Comment by SlimeNull** [comment]
晚上再弄 (✿◡‿◡)
忙活了一晚上了, 还没睡觉呢喵, 我先去睡觉

**Comment by AzideCupric** [comment]
感觉确实有这个必要，api目录实在是安排得过于没有规律
我翻文档的时候只看见send_group_forward_msg，没注意到send_private_forword_msg居然在最下面，差点以为go-cqhttp还没支持私聊合并转发

感觉api可以按这样分类(粗略想法):

## Bot账号

获取登录号信息
设置登录号资料

获取在线机型
设置在线机型

获取当前账号在线客户端列表

## 好友信息

获取陌生人信息
获取好友列表
获取单向好友列表

## 好友操作

删除好友
删除单向好友
上传私聊文件

## 消息

获取消息
发送消息
撤回消息

发送私聊消息
发送群消息

获取合并转发内容
发送合并转发 ( 好友 )
发送合并转发 ( 群 )

## 图片

获取图片信息
检查是否可以发送图片
图片 OCR

## 语音

获取语音
检查是否可以发送语音

## 群信息

获取群信息
获取群列表
获取群成员列表

获取群成员信息
获取群荣誉信息
获取群系统消息
获取群文件系统信息

获取群根目录文件列表
获取群子目录文件列表
获取群文件资源链接

获取群公告

获取群 @全体成员 剩余次数

## 群设置

设置群名
设置群头像
设置群管理员
设置群名片 ( 群备注 )

发送群公告

处理加好友请求
处理加群请求／邀请

## 群操作

群组单人禁言
群组匿名用户禁言
群组全员禁言

上传群文件
创建群文件文件夹
删除群文件文件夹
删除群文件

获取精华消息列表
设置精华消息
移出精华消息
获取群消息历史记录

群打卡

群组匿名

标记消息已读

设置群组专属头衔

群组踢人
退出群组

## go-cqhttp相关

检查链接安全性

下载文件到缓存目录

获取 Cookies
获取 CSRF Token
获取 QQ 相关接口凭证

获取版本信息
获取状态

重启 go-cqhttp

清理缓存

重载事件过滤器

获取中文分词 ( 隐藏 API )
对事件执行快速操作 ( 隐藏 API )

**Comment by qianjunakasumi** [comment]
可以问问 @SlimeNull 目前的进度（

**Comment by SlimeNull** [comment]
我超, 咕咕咕了

**Comment by SlimeNull** [comment]
这就去整

**Comment by SlimeNull** [comment]
整好了 https://github.com/ishkong/go-cqhttp-docs/pull/125

**Comment by qianjunakasumi** [comment]
辛苦了喵（

**Comment by AzideCupric** [comment]
好哦

**Comment by SlimeNull** [comment]
💕ヾ(≧▽≦*)o💕

**Comment by SlimeNull** [comment]
PR 已被 merge, 可以关闭这个 issue 了
