### ISSUE TITLE
GitHub Pages 404

### ISSUE THREAD

**Issue by sam01101** [ishkong/go-cqhttp-docs#64]
危
![image](https://user-images.githubusercontent.com/25792361/154855463-ac1b9645-805b-476b-a426-820b1993a7b4.png)

@ishkong 修一下CNAME，我不知道发送什么事了

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/154855529-a0286bbd-f43c-4d93-a288-ff15d3789b3f.png)

原始链接都露出来了

**Comment by ishkong** [comment]
Fixed in 55ac56d
