### ISSUE TITLE
考虑删除简介

### ISSUE THREAD

**Issue by qianjunakasumi** [ishkong/go-cqhttp-docs#87]
目前看来简介和主仓库是一样的，感觉复制一份到文档有点多余（
https://docs.go-cqhttp.org/guide/#go-cqhttp

**Comment by SlimeNull** [comment]
并不多余, 如果陌生人在网上搜索的话, 首先看到的可能不是 Github 仓库, 而是这份文档. 所以最好在文档中写的非常清楚才行

**Comment by qianjunakasumi** [comment]
这个无所谓，主要是同步复制异步，更新可能不及时，并且不是在主页面，SEO权重相对GitHub仓库可能也不足，但这是一个非常老的 issue 了，我就直接关了
