### ISSUE TITLE
建议 在API页面中添加access token的传递方式

### ISSUE THREAD

**Issue by ahjsrhj** [ishkong/go-cqhttp-docs#90]
尝试使用http请求发送消息，不知道Access Token该以什么字段放在何处，
尝试过在Header上配置各种组合均无效，经过搜索在 https://github.com/Mrs4s/go-cqhttp/issues/489 这条issues上得知配在url params上以access_token的形式。
文档内没有地方标明此种调用方式的参数配置

**Comment by SlimeNull** [comment]
在加了在加了 (我已经提 PR 了 (*/ω＼*)

https://github.com/ishkong/go-cqhttp-docs/pull/109

**Comment by SlimeNull** [comment]
这个 issue 可以 close 了

**Comment by ahjsrhj** [comment]
感谢处理
